### ISSUE TITLE
API proposal

### ISSUE THREAD

**Issue by marten** [zooniverse/nero#17]
Right now Nero is a standalone agent that listens to the AWS Kinesis stream, runs built-in code to update its internal database, and makes API calls back to Panoptes if a subject needs to be retired.

This ticket plans out an API to 1) make Nero's internal database visible to outside parties and 2) move that "built-in code" to separately hosted web services (which could be stateless and hosted on AWS Lambda).
# General API

There are three main pieces of data Nero tracks: the workflow, the subject (within the workflow), and the user (within the workflow).
- As an example, the subject is where you'd store information about consensus-so-far. 
- The user is where you'd store competency information (in case you're able to track this).
- The workflow is a good place to store a list of known highly-competent users (which you can keep updated as you update the users).

All three of these pieces of data are queryable through Nero's API:
### `GET /workflows/123/users/1`
# External Algorithm API

Right now the decision algorithms are built into Nero. To decouple this, in the future Nero will post to your service (at a URL that we can configure) the following JSON:

```
{
  workflow: {...}
  subject: {...}
  user: {...},
  classification: {...}
}
```

Nero expects the response body to be a JSON blob with the updated values for workflow, subject and user data. Additionally, a list of actions to be performed can be returned to Nero:

```
{
  workflow: {...}
  subject: {...}
  user: {...},
  action: [{...}, ...]
}
```
- Updated values for workflow, subject and user will replace the existing values.
## Supported actions

Right now Nero can only retire a subject. To do that, return an action of 'retire' with any string as the reason.

```
{action: 'retire', reason: 'consensus'}
```

In the future we also want to add task assignment, which means we enqueue a subject to be classified by a user. We still need to build support for this in Panoptes before Nero will be able to do this though. The action JSON for this might be something along these lines:

```
{action: 'enqueue', user_ids: [1, 2, 3, 4]}
```

Other ideas we have are push notifications to users, either in-browser, by email or (far future) in mobile apps.

**Comment by alexbfree** [comment]
Looks good. Wondering if user information should exist at a level above the workflow though? for tracking a user over time or across projects.

Another question - since this API delegates a lot of power to the caller, what validation will be needed to ensure the response is valid? will there need to be warnings/safeguards when things are deleted? Also what about security, how will this service be secured?

**Comment by marten** [comment]
Keeping information contained to a workflow-specific level means that we don't really need to do much validation. All an algorithm can do is remove it's own knowledge. We may want to put some thresholds so that you can't enqueue for thousands of users.

I think the generic api will be secured by OAuth tokens that Panoptes hands out (Nero can send them to Panoptes for verification that a user does indeed have owner-level access to that workflow or something). 

The external API is where Nero calls some other service, so authentication there would be up to the receiving party, but probably just HTTPS is good enough, optionally with an unguessable token in the URL.

**Comment by crowston** [comment]
Does Nero interpret the subject, workflow and user information, or are those just blob for the endpoint to define and interpret as it wants?

**Comment by alexbfree** [comment]
I understand where you are coming from, and think that is a sensible approach, but doesn't that prevent you asking questions like "has this user seen this subject before (ever)?" or "what is this user's classification accuracy (over all time)?". 

BTW another question:
Was just wondering _when_ in the classification lifecycle will this external algorithm hook be called? Is there a single hook point or more than one?

**Comment by marten** [comment]
@crowston No interpretation happening, just a generic data store for the endpoint to use (so that end points don't need to have a database of their own).

**Comment by marten** [comment]
@alexbfree after the classification was first completed. Usually soon after (on the order of seconds), but the front-end will be doing something else by the time Nero is doing work.
