### ISSUE TITLE
Update Space Warps algorithm for SWDemo classifications

### ISSUE THREAD

**Issue by marten** [zooniverse/nero#28]

**Comment by aprajita** [comment]
Hi @marten 
I'm behind schedule, and have asked the SW pi's & moderators to supply classifications on the test subjects currently in the workflow this morning. I hope we'll have about ~7users worth of classifications next week.
thanks
aprajita.

**Comment by marten** [comment]
That's okay, there's already a few in there and that plus the workflow definition itself is enough for me to get started.
